config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :posts
  # get '/posts', to: 'posts#index'
  # get '/posts/:id', to: 'posts#show'
  # get '/posts/new', to: 'posts#new'
  # get '/posts/:id/edit', to: 'posts#edit'
  # post '/posts/:id', to: 'posts#create'
  # put '/posts/:id', to: 'posts#update'
  # put '/posts/:id', to: 'posts#update'
  resources :authors, except: [:edit, :update, :delete]

  namespace :api do 
    resources :posts, defaults: { format: 'json' }
    resources :authors, defaults: { format: 'json' }
    resources :posts do 
      resources :comments, only: [:index, :show] #, controller: ''
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord 
    PHONE_REGEXP = /\(?[0-9]{3}\)?-[0-9]{3}-[0-9]{3}/
    ## Associations 
    has_many :posts, dependent: :nullify
    ## Validations
    validates :first_name, presence: true 
    validates :last_name, presence: true 
    validates_format_of :phone_number, with: PHONE_REGEXP, message: 'Phone number should be in xxx-xxx-xxx format'

    def full_name 
        "#{self.first_name} #{last_name}"
    end
end

app/models/categories_post.rb
class CategoriesPost < ApplicationRecord 
    belongs_to :category 
    belongs_to :post
end

app/models/category.rb
class Category < ApplicationRecord 
    has_many :categories_post 
    has_many :posts, through: :categories_post # dependent
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy

    has_many :categories_post
    has_many :categories, through: :categories_post

    validates :content, presence: true
    validates :title, presence: true, uniqueness: true

    has_one :tag

    belongs_to :author, optional: true # TODO: optional true

    # scope :title_logner_than_n_characters, -> { where("LENGTH(content) > 10") }
    scope :title_longer_than_n_characters, ->(n) { where("LENGTH(content) > ?", n) }
end

app/models/tag.rb
class Tag < ApplicationRecord 
    belongs_to :post
end

app/controllers/api/authors_controller.rb
class ::Api::AuthorsController < ActionController::API
    def index 
        @authors = Author.all
        render json: @authors, status: :ok
    end 

    def show
        @author = Author.find(params[:id])
        render json: @author, status: :ok
    end

    def create
        @author = Author.new(author_params)
        result = if @author.save
                    { json: @author, status: :created }
                 else
                    { json: @author.errors.messages, status: :bad_request }
                 end
        render result 
    end

    private

    def author_params 
        params.require(:author).permit(:first_name, :last_name, :phone_number)
    end
end

app/controllers/api/comments_controller.rb
class ::Api::CommentsController < ApplicationController 
    before_action :set_post
    before_action :set_comment, only: :show

    def index 
        post_comments = @post.comments 
        render json: post_comments, status: :ok
    end

    def show 
        render json: @comment, status: :ok
    end

    private 

    def set_post 
        @post = Post.find(params[:post_id])
    end

    def set_comment
        @comment = @post.comments.find(params[:id])
    end
end

app/controllers/api/posts_controller.rb
class ::Api::PostsController < ActionController::API
    def index 
        @posts = Post.all
        render json: @posts, status: :ok
    end 

    def show
        @post = Post.find(params[:id])
        render json: @post, status: :ok
    end

    def create
        @post = Post.new(post_params)
        result = if @post.save
                    { json: @post, status: :created }
                 else
                    { json: @post.errors.messages, status: :bad_request }
                 end
        render result 
    end

    def update 
        @post = Post.find(params[:id])
        result = if @post.update(post_params)
                    { json: @post, status: :ok }
                 else
                   { json: @post.errors.messages, status: :bad_request }
                 end

        render result
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        # head :ok
        render json: Post.all, status: :ok
    end

    private

    def post_params 
        params.require(:post).permit(:content, :title)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController 
    def index 
        @authors = Author.all
    end 

    def show
        @author = Author.find(params[:id])
    end

    def new
        @author = Author.new
    end

    def create
        @author = Author.new(author_params)
        if @author.save
            redirect_to authors_path 
        else
            render :new
        end
    end

    private

    def author_params 
        params.require(:author).permit(:first_name, :last_name, :phone_number)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController 
    def index 
        @posts = Post.all
    end 

    def show
        @post = Post.find(params[:id])
        @post_author = @post.author&.full_name
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to posts_path 
        else
            render :new
        end
    end

    def edit 
        @post = Post.find(params[:id])
    end

    def update 
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to posts_path 
        else
            render :edit
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end

    private

    def post_params 
        params.require(:post).permit(:content, :title, :author_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_form.html.erb
<%= form_for author do |f| %>
    <%= f.label :first_name, class: 'form-label' %>
    <%= f.text_field :first_name, style: 'display: block; margin-bottom: 10px;', class: 'form-group' %>
   
    <%= f.label :last_name, class: 'form-label' %>
    <%= f.text_field :last_name, style: 'display: block; margin-bottom: 10px;', class: 'form-group' %>
   
    <%= f.label :phone_number, class: 'form-label' %>
    <%= f.text_field :phone_number, style: 'display: block; margin-bottom: 10px;', class: 'form-group' %>
   
   
    <%= f.submit :submit, class: 'btn btn-primary' %>
<% end %> 

app/views/authors/index.html.erb
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Author fullname</th>
        </tr>
    </thead>
     <tbody>
        <%- @authors.each do |author|%>
            <tr>
                <th scope="row"><%= author.id %></th>
                <td><%= link_to "#{author.first_name} #{author.last_name}", author_path(author) %></td>
                <br>
                <hr/>
            </tr>
        <% end %>
    </tbody>
</table>
<br>
<%= link_to 'Create new author', new_author_path, class: 'btn btn-primary' %> 

app/views/authors/new.html.erb
<%= render 'form', author: @author %>

app/views/authors/show.html.erb
<strong>First name:</strong>
<%= @author.first_name %>
<strong>Last name:</strong>
<%= @author.last_name %>
<strong>Phone number:</strong>
<%= @author.phone_number %>

<br>
<%= link_to 'To index', authors_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyCourse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='container'>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for post do |f| %>
    <%= f.label :content, class: 'form-label' %>
    <%= f.text_field :content, style: 'display: block; margin-bottom: 10px;', class: 'form-group' %>
    <div class='form-group'>
        <%= f.select(:author_id,Author.all.map { |e| [e.full_name, e.id] }, class: 'form-control') %>
    </div>
    <%= f.submit :submit, class: 'btn btn-primary' %>
<% end %> 

app/views/posts/edit.html.erb
<%= render 'form', post: @post %> 

app/views/posts/index.html.erb
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Content</th>
            <th scope="col">Action 1</th>
            <th scope="col">Action 2</th>
        </tr>
    </thead>
     <tbody>
        <%- @posts.each do |post|%>
            <tr>
                <th scope="row"><%= post.id %></th>
                <td><%= link_to post.content, post_path(post) %></td>
                <td><%= link_to 'Edit', edit_post_path(post), class: "btn btn-primary" %></td>
                <td><%= link_to 'Delete', post, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %></td>
                <br>
                <hr/>
            </tr>
        <% end %>
    </tbody>
</table>
<br>
<%= link_to 'Create new post', new_post_path, class: 'btn btn-primary' %> 

<strong>Tags</strong>
<% @posts.includes(:tag).each do |post| %> 
    <%= post.tag.name %>
    <hr/>
<% end %>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<strong>Title:</strong>
<%= @post.content %>
<br/>
<strong>Author:</strong>
<%= @post_author || 'N/D'  %>
<br>
<%= link_to 'To index', posts_path %> 